### ISSUE TITLE
Missing authorization header or cookie

### ISSUE THREAD

**Issue by fazaamajdeddine** [davydocsurg/chat-server#1]
when im trying to test my service after login and in the postman , there is a generated cookie added in the header ,
even that the cookie token was in the authorization header i get 401 unauthorized :
error:
`{
    "code": 401,
    "message": "Missing authorization header or cookie",
    "stack": "Error: Missing authorization header or cookie\n    at /home/lenovo/backend-palmyra/kids-service/src/middleware/index.ts:44:21\n    at Generator.next (<anonymous>)\n    at /home/lenovo/backend-palmyra/kids-service/src/middleware/index.ts:8:71\n    at new Promise (<anonymous>)\n    at __awaiter (/home/lenovo/backend-palmyra/kids-service/src/middleware/index.ts:4:12)\n    at authMiddleware (/home/lenovo/backend-palmyra/kids-service/src/middleware/index.ts:29:86)\n    at Layer.handle [as handle_request] (/home/lenovo/backend-palmyra/kids-service/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/lenovo/backend-palmyra/kids-service/node_modules/express/lib/router/route.js:149:13)\n    at Route.dispatch (/home/lenovo/backend-palmyra/kids-service/node_modules/express/lib/router/route.js:119:3)\n    at Layer.handle [as handle_request] (/home/lenovo/backend-palmyra/kids-service/node_modules/express/lib/router/layer.js:95:5)"
`
![Screenshot from 2024-11-24 13-19-44](https://github.com/user-attachments/assets/73013d7a-58c0-463c-bf6b-eedbbeeba9f5)

my auth middlware:
`
import { Request, Response, NextFunction, ErrorRequestHandler } from "express";
import jwt from "jsonwebtoken";
import { ApiError } from "../utils";
import config from "../config/config";

interface TokenPayload {
    id: string;
    name: string;
    email: string;
    iat: number;
    exp: number;
}

interface IUser {
    _id: string;
    name: string;
    email: string;
    password: string;
    createdAt: Date;
    updatedAt: Date;
}

export interface AuthRequest extends Request {
    user: IUser;
}

const jwtSecret = config.JWT_SECRET as string;

const authMiddleware = async (
    req: AuthRequest,
    res: Response,
    next: NextFunction
) => {
    const authHeader = req.headers.authorization;
    if (!authHeader) {
        return next(new ApiError(401, "Missing authorization header"));
    }

    const [, token] = authHeader.split(" ");
    try {
        const decoded = jwt.verify(token, jwtSecret) as TokenPayload;
        console.log("Received Token:", token);

        req.user = {
            _id: decoded.id,
            email: decoded.email,
            createdAt: new Date(decoded.iat * 1000),
            updatedAt: new Date(decoded.exp * 1000),
            name: decoded.name,
            password: "",
        };
        return next();
    } catch (error) {
        console.error(error);
        return next(new ApiError(401, "Invalid token"));
    }
};

const errorConverter: ErrorRequestHandler = (err, req, res, next) => {
    let error = err;
    if (!(error instanceof ApiError)) {
        const statusCode =
            error.statusCode ||
            (error instanceof Error
                ? 400 // Bad Request
                : 500); // Internal Server Error
        const message =
            error.message ||
            (statusCode === 400 ? "Bad Request" : "Internal Server Error");
        error = new ApiError(statusCode, message, false, err.stack.toString());
    }
    next(error);
};

const errorHandler: ErrorRequestHandler = (err, req, res, next) => {
    let { statusCode, message } = err;
    if (process.env.NODE_ENV === "production" && !err.isOperational) {
        statusCode = 500; // Internal Server Error
        message = "Internal Server Error";
    }

    res.locals.errorMessage = err.message;

    const response = {
        code: statusCode,
        message,
        ...(process.env.NODE_ENV === "development" && { stack: err.stack }),
    };

    if (process.env.NODE_ENV === "development") {
        console.error(err);
    }

    res.status(statusCode).json(response);
    next();
};

export { authMiddleware, errorConverter, errorHandler };
`
can you help me resolve this issue

**Comment by lvanish** [comment]
Did you find the bug yet?
